import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, resolve, sep } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import {
  countByteFenceLines,
  deriveByteFenceCandidate,
  findByteOccurrences,
  hasUtf8Bom,
  parseByteFenceIntent
} from "../../../src/core/bytefence-contract.js";
import { evaluateByteFence } from "../../../src/core/bytefence-evaluate.js";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const corpusRoot = resolve(repoRoot, "examples/bytefence");
const manifest = JSON.parse(readFileSync(resolve(corpusRoot, "corpus-v0.1.json"), "utf8"));
const policyBytes = readFileSync(resolve(repoRoot, "policies/bytefence-default.json"));

test("the generated ByteFence corpus is byte-for-byte current", () => {
  const result = spawnSync(
    process.execPath,
    ["scripts/bytefence/generate-corpus.js", "--check"],
    { cwd: repoRoot, encoding: "utf8" }
  );
  assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
  assert.match(result.stdout, /7 cases, 28 generated files/);
});

test("the manifest records every artifact's exact size and SHA-256", () => {
  assert.equal(manifest._type, "ByteFenceAdversarialCorpus/v0.1");
  assert.equal(manifest.version, "0.1.0");
  assert.equal(manifest.hashAlgorithm, "sha256");
  assert.equal(manifest.cases.length, 7);

  for (const corpusCase of manifest.cases) {
    for (const artifact of Object.values(corpusCase.artifacts)) {
      const path = resolveCorpusPath(artifact.path);
      const bytes = readFileSync(path);
      assert.equal(bytes.length, artifact.bytes, `${corpusCase.id}: ${artifact.path} size`);
      assert.equal(sha256(bytes), artifact.sha256, `${corpusCase.id}: ${artifact.path} digest`);
      if (artifact.path.endsWith(".bin")) {
        assert.equal(
          countByteFenceLines(bytes),
          artifact.lines,
          `${corpusCase.id}: ${artifact.path} line count`
        );
      }
    }
  }
});

test("all corpus cases produce their pinned ByteFence decision", async (t) => {
  for (const corpusCase of manifest.cases) {
    await t.test(corpusCase.id, () => {
      const result = evaluateCase(corpusCase);
      assert.equal(result.status, corpusCase.expectation.status);
      assert.equal(result.allowed, corpusCase.expectation.allowed);
      assert.equal(result.exitCode, corpusCase.expectation.exitCode);
      assert.equal(
        result.effectiveGuaranteeLevel,
        corpusCase.expectation.effectiveGuaranteeLevel
      );
      assert.deepEqual(
        result.findings.map((finding) => finding.id).sort(),
        [...corpusCase.expectation.findingCodes].sort()
      );
    });
  }
});

test("unique anchors have one independently derived expected candidate", () => {
  for (const corpusCase of manifest.cases) {
    const intentBytes = readArtifact(corpusCase, "intent");
    const intent = parseByteFenceIntent(intentBytes);
    const preimage = readArtifact(corpusCase, "preimage");
    const occurrences = findByteOccurrences(preimage, Buffer.from(intent.oldText, "utf8"));
    const expectedArtifact = corpusCase.artifacts.expectedCandidate;

    if (!expectedArtifact) {
      assert.equal(corpusCase.id, "ambiguous-occurrences-denied");
      assert.equal(occurrences.length, 2);
      continue;
    }

    assert.equal(occurrences.length, 1, corpusCase.id);
    const derived = deriveByteFenceCandidate(preimage, intent);
    const expectedCandidate = readArtifact(corpusCase, "expectedCandidate");
    const proposedCandidate = readArtifact(corpusCase, "candidate");
    assert.deepEqual(derived, expectedCandidate, `${corpusCase.id}: exact derivation`);
    assert.equal(
      proposedCandidate.equals(expectedCandidate),
      corpusCase.assertions.candidateMatchesExactDerivation,
      `${corpusCase.id}: proposed-vs-derived candidate`
    );
  }
});

test("the synthetic truncation fixture is exactly 377-to-58 lines", () => {
  const corpusCase = findCase("synthetic-truncation-377-to-58");
  const preimage = readArtifact(corpusCase, "preimage");
  const proposed = readArtifact(corpusCase, "candidate");
  const expected = readArtifact(corpusCase, "expectedCandidate");
  assert.equal(countByteFenceLines(preimage), 377);
  assert.equal(countByteFenceLines(proposed), 58);
  assert.equal(countByteFenceLines(expected), 377);
  assert.ok(proposed.includes(Buffer.from("line-024: mode=after", "utf8")));
  assert.ok(!proposed.includes(Buffer.from("line-059:", "utf8")));
  assert.ok(expected.includes(Buffer.from("line-377:", "utf8")));
});

test("the Vibe fixture isolates one LF rewritten outside the declared range", () => {
  const corpusCase = findCase("vibe-mixed-eol-out-of-scope");
  const preimage = readArtifact(corpusCase, "preimage");
  const proposed = readArtifact(corpusCase, "candidate");
  const expected = readArtifact(corpusCase, "expectedCandidate");
  const preimageEol = countEol(preimage);
  const proposedEol = countEol(proposed);
  const expectedEol = countEol(expected);

  assert.deepEqual(preimageEol, { crlf: 3, isolatedLf: 1, isolatedCr: 0 });
  assert.deepEqual(expectedEol, preimageEol);
  assert.deepEqual(proposedEol, { crlf: 4, isolatedLf: 0, isolatedCr: 0 });
  assert.ok(expected.includes(Buffer.from('target = "after"', "utf8")));
  assert.ok(proposed.includes(Buffer.from('target = "after"', "utf8")));
  assert.ok(!proposed.equals(expected));
});

test("BOM removal is distinguished from the intended local edit", () => {
  const corpusCase = findCase("utf8-bom-removal-denied");
  const preimage = readArtifact(corpusCase, "preimage");
  const proposed = readArtifact(corpusCase, "candidate");
  const expected = readArtifact(corpusCase, "expectedCandidate");
  assert.equal(hasUtf8Bom(preimage), true);
  assert.equal(hasUtf8Bom(expected), true);
  assert.equal(hasUtf8Bom(proposed), false);
  assert.deepEqual(proposed, expected.subarray(3));
});

test("NFC/NFD bytes outside the ASCII anchor remain byte-significant", () => {
  const corpusCase = findCase("unicode-nfc-nfd-out-of-scope");
  const preimage = readArtifact(corpusCase, "preimage");
  const proposed = readArtifact(corpusCase, "candidate");
  const expected = readArtifact(corpusCase, "expectedCandidate");
  const nfd = Buffer.from("cafe\u0301", "utf8");
  const nfc = Buffer.from("caf\u00e9", "utf8");
  const astral = Buffer.from("\u{10400}", "utf8");

  assert.ok(preimage.includes(nfd));
  assert.ok(preimage.includes(nfc));
  assert.ok(expected.includes(nfd));
  assert.ok(proposed.includes(nfc));
  assert.ok(!proposed.includes(nfd));
  assert.ok(preimage.includes(astral));
  assert.ok(expected.includes(astral));
  assert.ok(proposed.includes(astral));
});

test("an exact full-target candidate remains policy-denied", () => {
  const corpusCase = findCase("full-target-rewrite-denied");
  const proposed = readArtifact(corpusCase, "candidate");
  const expected = readArtifact(corpusCase, "expectedCandidate");
  const result = evaluateCase(corpusCase);
  assert.deepEqual(proposed, expected);
  assert.match(proposed.toString("utf8"), /agent_claim=approved/);
  assert.equal(result.status, "deny");
  assert.equal(result.effectiveGuaranteeLevel, "OUT_OF_SCOPE");
  assert.deepEqual(
    result.findings.map((finding) => finding.id),
    ["change.fullTargetDenied", "change.deletionRatioExceeded"]
  );
});

function evaluateCase(corpusCase) {
  return evaluateByteFence({
    preimage: readArtifact(corpusCase, "preimage"),
    candidate: readArtifact(corpusCase, "candidate"),
    intentBytes: readArtifact(corpusCase, "intent"),
    policyBytes,
    workspaceId: "bytefence-corpus-v0.1",
    observedAt: "2026-07-13T00:00:00Z"
  });
}

function findCase(id) {
  const corpusCase = manifest.cases.find((entry) => entry.id === id);
  assert.ok(corpusCase, `Missing corpus case: ${id}`);
  return corpusCase;
}

function readArtifact(corpusCase, name) {
  const artifact = corpusCase.artifacts[name];
  assert.ok(artifact, `${corpusCase.id}: missing ${name} artifact`);
  return readFileSync(resolveCorpusPath(artifact.path));
}

function resolveCorpusPath(path) {
  const absolutePath = resolve(corpusRoot, path);
  assert.ok(
    absolutePath.startsWith(`${corpusRoot}${sep}`),
    `Corpus artifact escapes root: ${path}`
  );
  return absolutePath;
}

function countEol(bytes) {
  let crlf = 0;
  let isolatedLf = 0;
  let isolatedCr = 0;
  for (let index = 0; index < bytes.length; index += 1) {
    if (bytes[index] === 0x0d && bytes[index + 1] === 0x0a) {
      crlf += 1;
      index += 1;
    } else if (bytes[index] === 0x0a) {
      isolatedLf += 1;
    } else if (bytes[index] === 0x0d) {
      isolatedCr += 1;
    }
  }
  return { crlf, isolatedLf, isolatedCr };
}

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}
